# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: 'OnPremAgentPool'

jobs:
- job: InstallJDK
  pool:
    name: 'OnPremAgentPool'
  steps:
  - task: UseJavaVersion@0
    inputs:
      version: '8'  # Specify the desired JDK version
      installationPath: $(Agent.ToolsDirectory)/java

- job: Build
  pool:
    name: 'OnPremAgentPool'
    dependsOn: InstallJDK
  steps:
  - script: |
      # Display agent capabilities for troubleshooting
      echo "Agent Capabilities:"
      printenv | grep AGENT_
    displayName: 'Diagnostic Logging'
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: 'default'  # Use the default JDK version installed by the "UseJavaVersion" task
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
  displayName: 'Build on pip-300 agent'
